# Generated by Django 5.2 on 2025-05-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("departure", models.CharField(max_length=10)),
                ("arrival", models.CharField(max_length=10)),
                ("aircraft_type", models.CharField(max_length=50)),
                ("aircraft_reg", models.CharField(blank=True, max_length=20)),
                ("flight_time", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "flight_type",
                    models.CharField(
                        choices=[
                            ("VFR", "VFR"),
                            ("IFR", "IFR"),
                            ("TRAINING", "Training"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="flight_images/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
