# Generated by Django 5.2 on 2025-05-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='airline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='arrival_gate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='arrival_spot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='departure_gate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='departure_spot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='landing_runway',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='landing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='scheduled_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='seat_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='takeoff_runway',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='takeoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
