# Generated by Django 5.2 on 2025-05-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightlog', '0002_flightlog_actual_arrival_flightlog_actual_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='flight_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='flight_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
